
image:
  file: .gitpod.Dockerfile

ports:
  # django server
  - port: 8000
    onOpen: open-preview
  - port: 8025
    onOpen: open-preview
  # PostgreSQL server
  - port: 5432
    onOpen: ignore


tasks:
  - name: Server
    init: > 
      pg_ctl status | grep PID  || pg_start &&  
      cd server && 
      pre-commit install && source .envs/.local/.django  && 
      source .envs/.local/.postgres && psql -c "CREATE DATABASE server"  && 
      python manage.py migrate && python manage.py create_test_data &&
      cd ..
    command: pg_ctl status | grep PID  || pg_start && cd server && python manage.py runserver 0.0.0.0:8000
  - command: redis-server

  - command: MailHog      
  - name: Vue Client
    init: > 
      cd client && 
      yarn && cd .. && 
      gp sync-done client-install
    command: > 
      cd client && 
      yarn serve
  - name: Vue Storybook
    init: gp sync-await client-install
    command: >
     cd client && 
     yarn storybook
  - command: >
      echo welcome
  - command: >
      echo -e "\e[36mWELCOM CONTRIBUTER!"

# command: 'createdb server -U postgres --password $POSTGRES_PASSWORD'
vscode:
  extensions:
    - vsls-contrib.codetour
    - octref.vetur
    - esbenp.prettier-vscode
