# Generated by Django 3.1.11 on 2021-05-20 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import server.schools.models
import server.utils.model_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=server.schools.models.random_slug, max_length=40, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=50)),
                ('zip_city', models.CharField(max_length=15)),
                ('school_code', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=150)),
                ('contact_phone', server.utils.model_fields.PhoneNumberField(max_length=15)),
                ('website', models.URLField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('grade_levels', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolMemeber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
