# Generated by Django 3.1.11 on 2021-05-30 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20210523_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmember',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_member', to='schools.school'),
        ),
    ]
