# Generated by Django 3.1.11 on 2021-05-23 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0002_auto_20210523_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
