# Generated by Django 3.1.11 on 2021-07-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210624_1022'),
        ('schools', '0003_auto_20210530_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updated_by_me_schools', to='users.coordinator'),
        ),
    ]
