# Generated by Django 3.1.11 on 2021-07-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20210701_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
