# Generated by Django 3.1.11 on 2021-07-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20210713_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='zip_city',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
