# Generated by Django 3.1.11 on 2021-07-25 11:42

from django.db import migrations, models
import server.schools.models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_auto_20210720_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=server.schools.models.random_slug, max_length=40, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=50)),
                ('school_code', models.IntegerField(unique=True)),
                ('grade_levels', models.JSONField()),
                ('longtitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('region', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('boys', models.IntegerField()),
                ('girls', models.IntegerField()),
                ('male_teachers', models.IntegerField()),
                ('female_teachers', models.IntegerField()),
                ('migzar', models.CharField(blank=True, max_length=50, null=True)),
                ('school_type', models.CharField(blank=True, max_length=50, null=True)),
                ('school_stages', models.CharField(blank=True, max_length=50, null=True)),
                ('authority_city', models.CharField(blank=True, max_length=50, null=True)),
                ('is_bagrut', models.BooleanField()),
                ('immigrants_percent', models.FloatField(blank=True, null=True)),
                ('tech_students_percent', models.FloatField(blank=True, null=True)),
                ('tech_diploma_eligible_percent', models.FloatField(blank=True, null=True)),
                ('special_education_percent', models.FloatField(blank=True, null=True)),
                ('social_economic_status', models.IntegerField(blank=True, null=True)),
                ('decile_tipuah_hativa_benaim', models.IntegerField(blank=True, null=True)),
                ('decile_tipuah_hativa_eliona', models.IntegerField(blank=True, null=True)),
                ('decile_tipuah_yesodi', models.IntegerField(blank=True, null=True)),
                ('ivhun_percent', models.FloatField(blank=True, null=True)),
                ('boys_army_enlist_rate', models.FloatField(blank=True, null=True)),
                ('girls_army_enlist_rate', models.FloatField(blank=True, null=True)),
                ('hatmada_percent', models.FloatField(blank=True, null=True)),
                ('drop_rate', models.FloatField(blank=True, null=True)),
                ('bagrut_eligible_percent', models.FloatField(blank=True, null=True)),
                ('bagrut_excelent_eligible_percent', models.FloatField(blank=True, null=True)),
                ('bagrut_english_5u_percent', models.FloatField(blank=True, null=True)),
                ('bagrut_math_5u_percent', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
