version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  master:  
    jobs:
      - run-tests:
          name: run tests

jobs:
  run-tests:
    docker:
      - image: cimg/python:3.9.6
        environment:
          CELERY_BROKER_URL: "redis://localhost:6379/0"
          DATABASE_URL: "postgres://postgres@127.0.0.1:5432/server"
          GITPOD_WORKSPACE_URL: "https://localhost"
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - python/install-packages:
          app-dir: server
          pip-dependency-file: requirements/local.txt
          pkg-manager: pip
      - run:
          name: Run tests
          command: cd server && pytest
