version: 2.1

orbs:
  python: circleci/python@1.4.0

workflows:
  master:  
    jobs:
      - run-tests:
          name: run tests
          context:
            - SERVER_TESTING_ENV_VARS

jobs:
  run-tests:
    executor:
      name: python/default
      tag: "3.9"
    working_directory: ~/server
    steps:
      - checkout
      - run:
          command: pip install -r requirements/local.txt
          name: Install local dependencies
      - run:
          name: Run tests
          command: pytest
