# Generated by Django 3.1.11 on 2021-09-06 05:59

from django.db import migrations, models
import django.db.models.deletion
import server.utils.model_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfUseDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=server.utils.model_fields.random_slug, max_length=40, unique=True)),
                ('document_name', models.CharField(blank=True, max_length=50)),
                ('document_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfUsePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods', to='termsofuse.termsofusedocument')),
            ],
        ),
    ]
