# Generated by Django 3.1.11 on 2021-09-09 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('termsofuse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfUseSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='termsofusedocument',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='termsofusedocument',
            name='updated',
        ),
        migrations.DeleteModel(
            name='TermsOfUsePeriod',
        ),
        migrations.AddField(
            model_name='termsofusesignature',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='termsofuse.termsofusedocument'),
        ),
        migrations.AddField(
            model_name='termsofusesignature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL),
        ),
    ]
