# Generated by Django 3.1.11 on 2021-07-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210727_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_time',
            new_name='created',
        ),
    ]
