# Generated by Django 3.1.11 on 2021-07-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210721_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
