# Generated by Django 3.1.11 on 2021-07-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images_b64',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
