# Generated by Django 3.1.11 on 2021-05-20 12:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import server.utils.model_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=server.utils.model_fields.random_slug, max_length=40, unique=True)),
                ('name', models.CharField(max_length=35)),
                ('target_audience', models.JSONField()),
                ('domain', models.CharField(max_length=55)),
                ('description', models.CharField(default='', max_length=400)),
                ('contact_name', models.CharField(default='', max_length=60)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='phone number must be between 9-15 digits', regex='^\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=server.utils.model_fields.random_slug, max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=250)),
                ('website_url', models.URLField()),
                ('name', models.CharField(max_length=50)),
                ('goal', models.CharField(max_length=250)),
                ('year_founded', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.CharField(max_length=50)),
                ('target_audience', models.JSONField()),
                ('number_of_employees', models.PositiveIntegerField()),
                ('nuber_of_members', models.PositiveIntegerField()),
                ('number_of_volunteers', models.PositiveIntegerField()),
                ('location_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address_city', models.CharField(max_length=150)),
                ('address_street', models.CharField(max_length=150)),
                ('address_house_num', models.CharField(max_length=4)),
                ('address_zipcode', models.CharField(max_length=9)),
                ('cities', models.JSONField()),
                ('districts', models.JSONField()),
                ('union_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMemeber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=server.utils.model_fields.random_slug, max_length=40, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rich_media', to='organizations.activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='originization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization'),
        ),
    ]
