# Generated by Django 3.1.11 on 2021-05-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210523_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='nuber_of_members',
            new_name='number_of_members',
        ),
    ]
