# Generated by Django 3.1.11 on 2021-06-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20210610_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(default='', max_length=550),
        ),
    ]
