# Generated by Django 3.1.11 on 2021-06-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20210613_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolactivitygroup',
            name='activity_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schoolactivitygroup',
            name='activity_website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolactivitygroup',
            name='description',
            field=models.CharField(max_length=550, verbose_name='description'),
        ),
    ]
