# Generated by Django 3.1.11 on 2021-06-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20210613_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolactivitygroup',
            name='activity_email',
        ),
        migrations.RemoveField(
            model_name='schoolactivitygroup',
            name='activity_website_url',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
