# Generated by Django 3.1.11 on 2021-06-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20210613_1554'),
        ('organizations', '0005_auto_20210610_1825'),
    ]

    operations = [
    ]
