# Generated by Django 3.1.11 on 2021-06-24 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210624_1022'),
        ('organizations', '0009_merge_20210614_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolactivitygroup',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_activity_groups', to='users.instructor'),
        ),
    ]
