# Generated by Django 3.1.11 on 2021-06-24 15:10

from django.db import migrations
import server.utils.model_fields

def gen_random_slug(apps, schema_editor):
    Event = apps.get_model('organizations', 'SchoolActivityGroup')
    for row in Event.objects.all():
        row.slug = server.utils.model_fields.random_slug()
        row.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_schoolactivitygroup_slug'),
    ]

    operations = [
        migrations.RunPython(gen_random_slug, reverse_code=migrations.RunPython.noop),
    ]
