# Generated by Django 3.1.11 on 2021-06-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_auto_20210624_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='originization',
            new_name='origanization',
        ),
    ]
