# Generated by Django 3.1.11 on 2021-06-29 09:13

from django.db import migrations, models
import server.utils.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_auto_20210629_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolactivityorder',
            name='slug',
            field=models.CharField(default=server.utils.model_fields.random_slug, max_length=40, unique=True),
        ),
    ]
