# Generated by Django 3.1.11 on 2021-07-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210624_1022'),
        ('organizations', '0016_auto_20210629_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolactivitygroup',
            name='consumers',
            field=models.ManyToManyField(blank=True, related_name='activity_groups', to='users.Consumer'),
        ),
    ]
