# Generated by Django 3.1.11 on 2021-07-11 07:37

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('organizations', '0017_auto_20210701_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
