# Generated by Django 3.1.11 on 2021-07-25 11:09

from django.db import migrations, models
import server.utils.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_auto_20210718_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=server.utils.model_fields.random_slug, max_length=40, unique=True)),
                ('organization_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(blank=True, max_length=4096, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('goal', models.CharField(blank=True, max_length=4096, null=True)),
                ('year_founded', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('target_audience', models.JSONField(blank=True, null=True)),
                ('number_of_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_members', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_volunteers', models.PositiveIntegerField(blank=True, null=True)),
                ('location_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_city', models.CharField(blank=True, max_length=256, null=True)),
                ('address_street', models.CharField(blank=True, max_length=256, null=True)),
                ('address_house_num', models.CharField(blank=True, max_length=30, null=True)),
                ('address_zipcode', models.CharField(blank=True, max_length=9, null=True)),
                ('cities', models.JSONField(blank=True, null=True)),
                ('districts', models.JSONField(blank=True, null=True)),
                ('union_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='address_house_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='organization',
            name='goal',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
