# Generated by Django 3.1.11 on 2021-07-25 11:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import server.utils.model_fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('organizations', '0021_auto_20210725_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=server.utils.model_fields.random_slug, max_length=40, unique=True)),
                ('activity_code', models.IntegerField()),
                ('name', models.CharField(max_length=550)),
                ('raw_name', models.CharField(max_length=550)),
                ('target_audience', models.JSONField()),
                ('domain', models.CharField(blank=True, choices=[('SCIENCE_AND_TECH', 'Science And Tech'), ('EXTREME_SPORTS', 'Extreme Sports'), ('FIELD', 'Field')], max_length=55, null=True)),
                ('organization_number', models.IntegerField()),
                ('organization_name', models.CharField(default='', max_length=1550)),
                ('target_gender', models.JSONField()),
                ('target_population', models.JSONField()),
                ('target_time', models.JSONField()),
                ('target_size', models.JSONField()),
                ('target_migzar', models.JSONField()),
                ('target_pikuah', models.JSONField()),
                ('proffesion', models.JSONField()),
                ('goal', models.CharField(default='', max_length=1550)),
                ('is_active', models.BooleanField()),
                ('activity_website_url', models.URLField(blank=True, null=True)),
                ('activity_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(default='', max_length=1550)),
                ('contact_name', models.CharField(default='', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='phone number must be between 9-15 digits', regex='^\\d{9,15}$')])),
                ('originization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
