# Generated by Django 3.1.11 on 2021-07-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0023_auto_20210725_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_website_url',
            field=models.URLField(blank=True, max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='importedactivity',
            name='activity_website_url',
            field=models.URLField(blank=True, max_length=750, null=True),
        ),
    ]
