# Generated by Django 3.1.11 on 2021-08-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0024_auto_20210727_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='domain',
            field=models.CharField(choices=[('SCIENCE_AND_TECH', 'Science And Tech'), ('EXTREME_SPORTS', 'Extreme Sports'), ('FIELD', 'Field'), ('OTHER', 'Other')], max_length=55, null=True),
        ),
    ]
