# Generated by Django 3.1.11 on 2021-08-12 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_auto_20210804_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='originization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='organizations.organization'),
        ),
    ]
