# Generated by Django 3.1.11 on 2021-11-14 09:09

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('connective_tags', '0001_initial'),
        ('organizations', '0027_auto_20210831_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='connective_tags.ConnectiveTaggedItem', to='connective_tags.ConnectiveTag', verbose_name='Tags'),
        ),
    ]
