# Generated by Django 3.1.11 on 2021-12-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0028_auto_20211114_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolactivitygroup',
            name='group_type',
            field=models.CharField(choices=[('CONTAINER_ONLY', 'Container Only'), ('DISABLED_CONSUMERS', 'Disabled Consumers'), ('NO_REGISTRATION', 'No Registration'), ('DEFAULT', 'Default')], default='DEFAULT', max_length=50, verbose_name='group type'),
        ),
    ]
