# Generated by Django 3.1.14 on 2022-02-07 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20210727_1616'),
        ('organizations', '0029_auto_20211223_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolactivityorder',
            name='ownership_type',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('SITE', 'Site')], default='SCHOOL', max_length=50, verbose_name='ownership type'),
        ),
        migrations.AlterField(
            model_name='schoolactivityorder',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_activity_orders', to='schools.school'),
        ),
    ]
