# Generated by Django 3.1.11 on 2021-08-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210714_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tour_complete',
            field=models.BooleanField(default=False),
        ),
    ]
