# Generated by Django 3.1.11 on 2021-08-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_tour_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_tour_complete',
            new_name='is_signup_complete',
        ),
    ]
