# Generated by Django 3.1.11 on 2021-08-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210811_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('USER', 'User')], default='USER', max_length=50, verbose_name='Type'),
        ),
    ]
