# Generated by Django 3.1.11 on 2021-09-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210831_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_of_use_acceptance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
