# Generated by Django 3.1.11 on 2021-09-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_terms_of_use_acceptance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='terms_of_use_acceptance_date',
        ),
    ]
