# Generated by Django 3.1.14 on 2022-03-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userbookmark'),
        ('users', '0015_auto_20220322_1304'),
    ]

    operations = [
    ]
