# Generated by Django 3.1.14 on 2022-03-23 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20220323_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='grade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
