# Generated by Django 3.1.14 on 2022-03-24 14:08

from django.db import migrations


def do_nothing(apps, schema_editor):
    pass


def add_coord_role(apps, schema_editor):
    Coordinator = apps.get_model("users", "Coordinator")

    for coordinator in Coordinator.objects.filter(user_type="COORDINATOR"):

        if (
            hasattr(coordinator, "school_member")
            and coordinator.school_member
            and coordinator.school_member.school
        ):
            print(f"Coordinator ID={coordinator.id}, email={coordinator.email}")
            school = coordinator.school_member.school
            if coordinator.roles.filter(role_code="COORDINATOR_ADMIN").exists():
                print("COORDINATOR_ADMIN role already exists")
            else:
                coordinator.roles.create(
                    role_code="COORDINATOR_ADMIN", school=school, site=coordinator.site
                )
                print("COORDINATOR_ADMIN applyed successfully")
        else:
            print(f"Could not find school for coordinator {coordinator.id}")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_consumerprofile_grade"),
    ]

    operations = [migrations.RunPython(add_coord_role, reverse_code=do_nothing)]
