PRIV_CONTENT_EDIT = "PRIV_CONTENT_EDIT"
PRIV_CONTENT_VIEW = "PRIV_CONTENT_VIEW"

PRIV_USER_CONSUMER_EDIT = "PRIV_USER_CONSUMER_EDIT"
PRIV_USER_CONSUMER_VIEW = "PRIV_USER_CONSUMER_VIEW"
PRIV_USER_COORDINATOR_EDIT = "PRIV_USER_COORDINATOR_EDIT"
PRIV_USER_INSTRUCTOR_EDIT = "PRIV_USER_INSTRUCTOR_EDIT"
PRIV_USER_INSTRUCTOR_VIEW = "PRIV_USER_INSTRUCTOR_VIEW"
PRIV_USER_INSTRUCTOR_VIEW_ALL = "PRIV_USER_INSTRUCTOR_VIEW_ALL"

PRIV_EVENT_ORDER_VIEW = "PRIV_EVENT_ORDER_VIEW"
PRIV_EVENT_ORDER_EDIT = "PRIV_EVENT_ORDER_EDIT"
PRIV_EVENT_ORDER_CREATE = "PRIV_EVENT_ORDER_CREATE"
PRIV_EVENT_ORDER_APPROVE = "PRIV_EVENT_ORDER_APPROVE"
PRIV_EVENT_VIEW = "PRIV_EVENT_VIEW"
PRIV_EVENT_EDIT = "PRIV_EVENT_EDIT"
PRIV_EVENT_EDIT_MY_ONLY = "PRIV_EVENT_EDIT_MY_ONLY"

PRIV_GROUP_MANAGE_ORGANIZATION_VIEW = "PRIV_GROUP_MANAGE_ORGANIZATION_VIEW"
PRIV_GROUP_MANAGE_ORGANIZATION_EDIT = "PRIV_GROUP_MANAGE_ORGANIZATION_EDIT"

PRIV_GROUP_MANAGE_SCHOOL_VIEW = "PRIV_GROUP_MANAGE_SCHOOL_VIEW"
PRIV_GROUP_MANAGE_SCHOOL_EDIT = "PRIV_GROUP_MANAGE_SCHOOL_EDIT"

PRIV_SCHOOL_VIEW = "PRIV_SCHOOL_VIEW"
PRIV_SCHOOL_EDIT = "PRIV_SCHOOL_EDIT"

PRIV_ACTIVITY_VIEW_ALL = "PRIV_ACTIVITY_VIEW_ALL"
PRIV_ACTIVITY_VIEW = "PRIV_ACTIVITY_VIEW"
PRIV_ACTIVITY_EDIT = "PRIV_ACTIVITY_EDIT"

# #### ROLES ##### #

ROLE_VENDOR_ADMIN = "VENDOR_ADMIN"
ROLE_COORDINATOR_ADMIN = "COORDINATOR_ADMIN"
ROLE_CONTENT_EDITOR = "CONTENT_EDITOR"
ROLE_INSTRUCTOR = "INSTRUCTOR"
ROLE_CUSTOMER_ADMIN = "CUSTOMER_ADMIN"

ROLES = {
    ROLE_VENDOR_ADMIN: frozenset(
        [
            PRIV_USER_INSTRUCTOR_EDIT,
            PRIV_USER_INSTRUCTOR_VIEW,
            PRIV_USER_CONSUMER_VIEW,
            PRIV_EVENT_ORDER_VIEW,
            PRIV_EVENT_ORDER_EDIT,
            PRIV_EVENT_ORDER_APPROVE,
            PRIV_EVENT_ORDER_CREATE,
            PRIV_EVENT_VIEW,
            PRIV_EVENT_EDIT,
            PRIV_EVENT_EDIT_MY_ONLY,
            PRIV_GROUP_MANAGE_ORGANIZATION_VIEW,
            PRIV_GROUP_MANAGE_ORGANIZATION_EDIT,
            PRIV_SCHOOL_VIEW,
            PRIV_ACTIVITY_VIEW,
        ]
    ),
    ROLE_COORDINATOR_ADMIN: frozenset(
        [
            PRIV_USER_CONSUMER_EDIT,
            PRIV_USER_CONSUMER_VIEW,
            PRIV_USER_COORDINATOR_EDIT,
            PRIV_USER_INSTRUCTOR_VIEW,
            PRIV_USER_INSTRUCTOR_VIEW_ALL,
            PRIV_EVENT_ORDER_VIEW,
            PRIV_EVENT_ORDER_EDIT,
            PRIV_EVENT_ORDER_CREATE,
            PRIV_EVENT_VIEW,
            PRIV_EVENT_EDIT,
            PRIV_EVENT_EDIT_MY_ONLY,
            PRIV_EVENT_VIEW,
            PRIV_EVENT_EDIT,
            PRIV_GROUP_MANAGE_SCHOOL_VIEW,
            PRIV_GROUP_MANAGE_SCHOOL_EDIT,
            PRIV_SCHOOL_VIEW,
            PRIV_ACTIVITY_VIEW,
            PRIV_ACTIVITY_VIEW_ALL,
        ]
    ),
    ROLE_CONTENT_EDITOR: frozenset([PRIV_CONTENT_EDIT, PRIV_CONTENT_VIEW]),
    ROLE_INSTRUCTOR: frozenset(
        [
            PRIV_CONTENT_VIEW,
            PRIV_USER_CONSUMER_VIEW,
            PRIV_USER_INSTRUCTOR_VIEW,
            PRIV_EVENT_VIEW,
            PRIV_EVENT_EDIT_MY_ONLY,
            PRIV_SCHOOL_VIEW,
        ]
    ),
    ROLE_CUSTOMER_ADMIN: frozenset(
        [
            PRIV_CONTENT_EDIT,
            PRIV_CONTENT_VIEW,
            PRIV_USER_CONSUMER_EDIT,
            PRIV_USER_CONSUMER_VIEW,
            PRIV_USER_COORDINATOR_EDIT,
            PRIV_USER_INSTRUCTOR_EDIT,
            PRIV_USER_INSTRUCTOR_VIEW,
            PRIV_USER_INSTRUCTOR_VIEW_ALL,
            PRIV_EVENT_ORDER_VIEW,
            PRIV_EVENT_ORDER_EDIT,
            PRIV_EVENT_ORDER_CREATE,
            PRIV_EVENT_ORDER_APPROVE,
            PRIV_EVENT_VIEW,
            PRIV_EVENT_EDIT,
            PRIV_EVENT_EDIT_MY_ONLY,
            PRIV_GROUP_MANAGE_ORGANIZATION_VIEW,
            PRIV_GROUP_MANAGE_ORGANIZATION_EDIT,
            PRIV_GROUP_MANAGE_SCHOOL_VIEW,
            PRIV_GROUP_MANAGE_SCHOOL_EDIT,
            PRIV_SCHOOL_VIEW,
            PRIV_SCHOOL_EDIT,
            PRIV_ACTIVITY_VIEW,
            PRIV_ACTIVITY_VIEW_ALL,
        ]
    ),
}
