# Generated by Django 3.1.11 on 2021-11-10 18:16

from django.db import migrations, models
import django.db.models.deletion
import server_addons.tenants.middlewares


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0004_alter_options_ordering_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectiveTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('site', models.ForeignKey(default=server_addons.tenants.middlewares.get_context_site_id, on_delete=django.db.models.deletion.RESTRICT, to='sites.site')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='ConnectiveTaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connective_tags_connectivetaggeditem_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('site', models.ForeignKey(default=server_addons.tenants.middlewares.get_context_site_id, on_delete=django.db.models.deletion.RESTRICT, to='sites.site')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connective_tags_connectivetaggeditem_items', to='connective_tags.connectivetag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
