# Generated by Django 3.1.14 on 2022-01-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connective_tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectivetag',
            name='category',
            field=models.CharField(default='general', max_length=30),
        ),
    ]
