# Generated by Django 3.1.14 on 2022-01-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connective_tags', '0002_connectivetag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivetag',
            name='slug',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
