# Generated by Django 3.1.11 on 2021-06-24 15:22

from django.db import migrations
import server.utils.model_fields

def gen_random_slug(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    for row in Event.objects.all():
        row.slug = server.utils.model_fields.random_slug()
        row.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210624_1022'),
    ]

    operations = [
        migrations.RunPython(gen_random_slug, reverse_code=migrations.RunPython.noop),
    ]