# Generated by Django 3.1.11 on 2021-06-24 15:22

from django.db import migrations, models
import server.utils.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210624_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(default=server.utils.model_fields.random_slug, max_length=40, unique=True),
        ),

    ]
