# Generated by Django 3.1.11 on 2021-07-11 12:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import server.utils.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210624_1022'),
        ('events', '0006_auto_20210711_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerEventFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=server.utils.model_fields.random_slug, max_length=40, unique=True)),
                ('general_notes', models.CharField(blank=True, max_length=400)),
                ('secondary_notes', models.CharField(blank=True, max_length=400)),
                ('general_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('secondary_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.consumer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
