# Generated by Django 3.1.11 on 2021-07-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210714_1121'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consumereventfeedback',
            constraint=models.UniqueConstraint(fields=('consumer', 'event'), name='unique consumer feedback'),
        ),
    ]
