# Generated by Django 3.1.11 on 2021-07-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_events_sequence_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='events_sequence_slug',
            new_name='recurring_events_slug',
        ),
    ]
