# Generated by Django 3.1.11 on 2021-07-28 12:04

from django.db import migrations, models
import django.db.models.deletion
import server.utils.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0024_auto_20210727_1319'),
        ('events', '0011_auto_20210728_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='recurring_events_slug',
        ),
        migrations.CreateModel(
            name='EventOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=server.utils.model_fields.random_slug, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('CANCELLED', 'Cancelled'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('DENIED', 'DENIED')], default='PENDING_APPROVAL', max_length=50, verbose_name='status')),
                ('recurrence', models.CharField(choices=[('ONE_TIME', 'One Time'), ('WEEKLY', 'Weekly')], default='ONE_TIME', max_length=50, verbose_name='recurrence')),
                ('locations_name', models.CharField(blank=True, max_length=250, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('school_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.schoolactivitygroup')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventorder'),
        ),
    ]
