# Generated by Django 3.1.11 on 2021-07-28 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210728_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventorder'),
        ),
        migrations.AlterField(
            model_name='eventorder',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'Cancelled'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING_APPROVAL', max_length=50, verbose_name='status'),
        ),
    ]
