# Generated by Django 3.1.11 on 2021-07-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20210728_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='status_reason',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
