# Generated by Django 3.1.11 on 2021-07-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventorder_status_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.eventorder'),
        ),
    ]
