# Generated by Django 3.1.11 on 2021-08-15 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0026_auto_20210812_1415'),
        ('events', '0015_auto_20210729_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorder',
            name='school_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.schoolactivitygroup'),
        ),
    ]
