# Generated by Django 3.1.11 on 2021-11-03 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_options_ordering_domain'),
        ('events', '0017_event_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumereventfeedback',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='sites.site'),
        ),
        migrations.AddField(
            model_name='event',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='sites.site'),
        ),
        migrations.AddField(
            model_name='eventorder',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='sites.site'),
        ),
    ]
