# Generated by Django 3.1.11 on 2021-12-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('ILLNESS', 'Illness'), ('WEATHER', 'Weather'), ('EXAM_SEASON', 'Exam Season'), ('COVID_19', 'COVID-19'), ('HOLIDAY', 'Holiday'), ('OTHER', 'Other')], max_length=200),
        ),
    ]
