# Generated by Django 3.1.14 on 2022-04-03 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0030_auto_20220207_0907'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0019_auto_20211223_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_instructors',
            field=models.ManyToManyField(blank=True, related_name='additional_instructor_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='filter_genders',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='filter_grades',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='eventorder',
            name='additional_instructors',
            field=models.ManyToManyField(blank=True, related_name='additional_instructor_event_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventorder',
            name='filter_genders',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventorder',
            name='filter_grades',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventorder',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_event_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventorder',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='school_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.schoolactivitygroup'),
        ),
    ]
