# Generated by Django 3.1.14 on 2022-04-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20210727_1616'),
        ('events', '0020_auto_20220403_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_event_orders', to='schools.school'),
        ),
    ]
