# Generated by Django 3.1.14 on 2022-04-05 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_vendor_role'),
        ('events', '0021_eventorder_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_events', to='users.instructor'),
        ),
    ]
